"""Adiciona restrição de unicidade na NF

Revision ID: 0b6816796852
Revises: 
Create Date: 2025-09-24 09:02:16.706038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b6816796852'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entradas_embalagem', schema=None) as batch_op:
        batch_op.alter_column('data_recebimento',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.create_unique_constraint(None, ['nf'])

    with op.batch_alter_table('saidas_embalagem', schema=None) as batch_op:
        batch_op.alter_column('data_saida',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
        batch_op.drop_column('unidade_medida')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saidas_embalagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_medida', mysql.VARCHAR(length=10), nullable=False))
        batch_op.alter_column('data_saida',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    with op.batch_alter_table('entradas_embalagem', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('data_recebimento',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))

    # ### end Alembic commands ###
