"""Altera colunas de data para datetime

Revision ID: d1e63aa8729d
Revises: d1592a28c680
Create Date: 2025-10-01 11:50:01.992607

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1e63aa8729d'
down_revision = 'd1592a28c680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entradas_embalagem', schema=None) as batch_op:
        batch_op.alter_column('pedido_compra',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entradas_embalagem', schema=None) as batch_op:
        batch_op.alter_column('pedido_compra',
               existing_type=sa.String(length=5),
               type_=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###
